name: Build and Deploy train-ticket-reservation

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Check Java Version
        run: |
          java -version
          mvn -version

      - name: Build Application
        run: mvn clean package -DskipTests

      # SonarQube Analysis
      - name: SonarQube Analysis
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      # Upload WAR/JAR as GitHub Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: train-ticket-reservation
          path: |
            target/*.war
            target/*.jar
